task_list = [
    "agronomy",
    "anatomy",
    "ancient_chinese",
    "arts",
    "astronomy",
    "business_ethics",
    "chinese_civil_service_exam",
    "chinese_driving_rule",
    "chinese_food_culture",
    "chinese_foreign_policy",
    "chinese_history",
    "chinese_literature",
    "chinese_teacher_qualification",
    "clinical_knowledge",
    "college_actuarial_science",
    "college_education",
    "college_engineering_hydrology",
    "college_law",
    "college_mathematics",
    "college_medical_statistics",
    "college_medicine",
    "computer_science",
    "computer_security",
    "conceptual_physics",
    "construction_project_management",
    "economics",
    "education",
    "electrical_engineering",
    "elementary_chinese",
    "elementary_commonsense",
    "elementary_information_and_technology",
    "elementary_mathematics",
    "ethnology",
    "food_science",
    "genetics",
    "global_facts",
    "high_school_biology",
    "high_school_chemistry",
    "high_school_geography",
    "high_school_mathematics",
    "high_school_physics",
    "high_school_politics",
    "human_sexuality",
    "international_law",
    "journalism",
    "jurisprudence",
    "legal_and_moral_basis",
    "logical",
    "machine_learning",
    "management",
    "marketing",
    "marxist_theory",
    "modern_chinese",
    "nutrition",
    "philosophy",
    "professional_accounting",
    "professional_law",
    "professional_medicine",
    "professional_psychology",
    "public_relations",
    "security_study",
    "sociology",
    "sports_science",
    "traditional_chinese_medicine",
    "virology",
    "world_history",
    "world_religions",
]

subject2name = {
    "agronomy": "农学",
    "anatomy": "解剖学",
    "ancient_chinese": "古汉语",
    "arts": "艺术学",
    "astronomy": "天文学",
    "business_ethics": "商业伦理",
    "chinese_history": "中国历史",
    "chinese_literature": "中国文学",
    "chinese_civil_service_exam": "中国公务员考试",
    "chinese_driving_rule": "中国驾驶规则",
    "chinese_food_culture": "中国饮食文化",
    "chinese_foreign_policy": "中国外交政策",
    "chinese_teacher_qualification": "中国教师资格",
    "clinical_knowledge": "临床知识",
    "college_actuarial_science": "大学精算学",
    "college_education": "大学教育学",
    "college_engineering_hydrology": "大学工程水文学",
    "college_law": "大学法律",
    "college_mathematics": "大学数学",
    "college_medical_statistics": "大学医学统计",
    "college_medicine": "大学医学",
    "computer_science": "计算机科学",
    "computer_security": "计算机安全",
    "conceptual_physics": "概念物理学",
    "construction_project_management": "建设工程管理",
    "economics": "经济学",
    "education": "教育学",
    "electrical_engineering": "电气工程",
    "elementary_chinese": "小学语文",
    "elementary_commonsense": "小学常识",
    "elementary_information_and_technology": "小学信息技术",
    "elementary_mathematics": "初等数学",
    "ethnology": "民族学",
    "food_science": "食品科学",
    "genetics": "遗传学",
    "global_facts": "全球事实",
    "high_school_biology": "高中生物",
    "high_school_chemistry": "高中化学",
    "high_school_geography": "高中地理",
    "high_school_mathematics": "高中数学",
    "high_school_physics": "高中物理学",
    "high_school_politics": "高中政治",
    "human_sexuality": "人类性行为",
    "international_law": "国际法学",
    "journalism": "新闻学",
    "jurisprudence": "法理学",
    "legal_and_moral_basis": "法律与道德基础",
    "logical": "逻辑学",
    "machine_learning": "机器学习",
    "management": "管理学",
    "marketing": "市场营销",
    "marxist_theory": "马克思主义理论",
    "modern_chinese": "现代汉语",
    "nutrition": "营养学",
    "philosophy": "哲学",
    "professional_accounting": "专业会计",
    "professional_law": "专业法学",
    "professional_medicine": "专业医学",
    "professional_psychology": "专业心理学",
    "public_relations": "公共关系",
    "security_study": "安全研究",
    "sociology": "社会学",
    "sports_science": "体育学",
    "traditional_chinese_medicine": "中医中药",
    "virology": "病毒学",
    "world_history": "世界历史",
    "world_religions": "世界宗教",
}

subject2category = {
    "agronomy": "Other",
    "anatomy": "STEM",
    "ancient_chinese": "specific",
    "arts": "Humanities",
    "astronomy": "STEM",
    "business_ethics": "Science",
    "chinese_history": "specific",
    "chinese_literature": "specific",
    "chinese_civil_service_exam": "specific",
    "chinese_driving_rule": "specific",
    "chinese_food_culture": "specific",
    "chinese_foreign_policy": "specific",
    "chinese_teacher_qualification": "specific",
    "clinical_knowledge": "STEM",
    "college_actuarial_science": "STEM",
    "college_education": "Science",
    "college_engineering_hydrology": "STEM",
    "college_law": "Humanities",
    "college_mathematics": "STEM",
    "college_medical_statistics": "STEM",
    "college_medicine": "STEM",
    "computer_science": "STEM",
    "computer_security": "STEM",
    "conceptual_physics": "STEM",
    "construction_project_management": "specific",
    "economics": "Science",
    "education": "Science",
    "electrical_engineering": "STEM",
    "elementary_chinese": "specific",
    "elementary_commonsense": "specific",
    "elementary_information_and_technology": "Other",
    "elementary_mathematics": "STEM",
    "ethnology": "specific",
    "food_science": "Other",
    "genetics": "STEM",
    "global_facts": "Humanities",
    "high_school_biology": "STEM",
    "high_school_chemistry": "STEM",
    "high_school_geography": "Science",
    "high_school_mathematics": "STEM",
    "high_school_physics": "STEM",
    "high_school_politics": "specific",
    "human_sexuality": "Other",
    "international_law": "Humanities",
    "journalism": "Science",
    "jurisprudence": "Humanities",
    "legal_and_moral_basis": "Other",
    "logical": "Humanities",
    "machine_learning": "STEM",
    "management": "Science",
    "marketing": "Science",
    "marxist_theory": "Humanities",
    "modern_chinese": "specific",
    "nutrition": "STEM",
    "philosophy": "Humanities",
    "professional_accounting": "Science",
    "professional_law": "Humanities",
    "professional_medicine": "STEM",
    "professional_psychology": "Science",
    "public_relations": "Science",
    "security_study": "Science",
    "sociology": "Science",
    "sports_science": "Other",
    "traditional_chinese_medicine": "specific",
    "virology": "STEM",
    "world_history": "Humanities",
    "world_religions": "Humanities",
}
